on:
  issues:
    types: [labeled]

jobs:
  invite:
    runs-on: ubuntu-latest
    steps:
      - name: Invite To Organisation
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.INVITE_TOKEN }}
          script: |
            const org = 'naomis-novas';
            const { owner, repo } = context.repo;
            const issue_number = context.issue.number;
            const label = context.payload.label.name;
            const { id: invitee_id, login: username } = context.payload.issue.user;

            if (label !== '✉️ misc: invite to org') {
              return;
            }

            const isMember = await github.rest.orgs.checkMembershipForUser({
              org,
              username,
            }).catch(() => null);

            if (isMember) {
              await github.rest.issues.createComment({
                issue_number,
                owner,
                repo,
                body: 'You are already a part of Naomi's Novas~!\n\nIf you haven't already, join our [Discord](https://chat.naomi.lgbt)!'
              });
            } else {
              await github.rest.orgs.createInvitation({
                org,
                invitee_id,
              })
              await github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner,
                repo,
                body: 'Invite sent~!\n\nBe sure to join our [Discord](https://chat.naomi.lgbt) too!'
              })
            }

            await github.rest.issues.update({
              owner,
              repo,
              issue_number,
              state: 'closed'
            });
